server:
  port: 8000

# database:
#   host: localhost
#   port: 3306
#   user: ""
#   password: ""
#   dbname: homeinsight

database:
  uri: "mongodb+srv://<username>:<password>@<cluster>.mongodb.net/?retryWrites=true&w=majority"
  dbname: "homeinsight"

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your_jwt_secret_key"
