# database:
#   host: localhost
#   port: 3306
#   user: ""
#   password: ""
#   dbname: homeinsight

server:
  port: 8000

database:
  uri: "mongodb+srv://homeinsightcore:Zj3l6zfaM43K3PpG@cluster0.9kecynk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  dbname: "homeinsight"

redis:
  host: clustercfg.homeinsight-core-cache.dxz4rf.use1.cache.amazonaws.com
  port: 6379
  password: ""
  db: 0
  tls_enabled: false
  tls_cert_file: ""

jwt:
  secret: "your_jwt_secret_key"
