server:
  port: 8000
database:
  host: localhost
  port: 3306
  user: ""
  password: ""
  dbname: homeinsight
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
jwt:
  secret: "your_jwt_secret_key"
