server:
  port: 8000

database:
  uri: ""
  dbname: homeinsight
  stale_threshold_days: 60 #2 months (60 days)

redis:
  host: ""
  port: 6379
  password: ""
  db: 0
  tls_enabled: false
  cache_ttl_days: 30 #1 month (30 days)

jwt:
  secret: ""

corelogic:
  client_key: ""
  client_secret: ""
  developer_email: ""
