name: Deploy Go App with Nginx and SSL to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 550487074506.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Go Docker Image
        run: |
          docker build -t go-language-repo .
          docker tag go-language-repo:latest 550487074506.dkr.ecr.us-east-1.amazonaws.com/go-language-repo:latest
          docker push 550487074506.dkr.ecr.us-east-1.amazonaws.com/go-language-repo:latest

      # - name: Build and Push Nginx Docker Image
      #   run: |
      #     docker build -t homeinsightcore_nginx -f Dockerfile.nginx .
      #     docker tag homeinsightcore_nginx:latest 882142483449.dkr.ecr.us-east-1.amazonaws.com/homeinsightcore_nginx:latest
      #     docker push 882142483449.dkr.ecr.us-east-1.amazonaws.com/homeinsightcore_nginx:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Log in to AWS ECR on the EC2 instance
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 550487074506.dkr.ecr.us-east-1.amazonaws.com

            # Pull the latest image
            sudo docker pull 550487074506.dkr.ecr.us-east-1.amazonaws.com/go-language-repo:latest
            
            # Stop and remove the old container if it exists
            sudo docker stop go-language || true
            sudo docker rm go-language || true
            
            # Run the new container
            sudo docker run -d --name go-language -p 8000:8000 550487074506.dkr.ecr.us-east-1.amazonaws.com/go-language-repo:latest
            