name: Deploy GO and Nginx to AWS EC2 via ECR

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: 882142483449.dkr.ecr.us-east-1.amazonaws.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build and Push Go Docker Image
        run: |
          docker build -t homeinsightcore -f Dockerfile .
          docker tag homeinsightcore:latest $ECR_REGISTRY/homeinsightcore:latest
          docker push $ECR_REGISTRY/homeinsightcore:latest
          docker inspect --format='Go Image Digest: {{index .RepoDigests 0}}' $ECR_REGISTRY/homeinsightcore:latest

      - name: Build and Push Nginx Docker Image
        run: |
          docker build -t homeinsightcore_nginx -f Dockerfile.nginx .
          docker tag homeinsightcore_nginx:latest $ECR_REGISTRY/homeinsightcore_nginx:latest
          docker push $ECR_REGISTRY/homeinsightcore_nginx:latest
          docker inspect --format='Nginx Image Digest: {{index .RepoDigests 0}}' $ECR_REGISTRY/homeinsightcore_nginx:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Logging in to ECR..."
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY

            echo "Pulling updated Docker images..."
            docker pull $ECR_REGISTRY/homeinsightcore:latest
            docker pull $ECR_REGISTRY/homeinsightcore_nginx:latest

            echo "Stopping old containers if running..."
            docker stop homeinsightcore || true && docker rm homeinsightcore || true
            docker stop nginx || true && docker rm nginx || true

            echo "Creating Docker network if not exists..."
            docker network inspect app-network >/dev/null 2>&1 || docker network create app-network

            echo "Creating necessary directories..."
            sudo mkdir -p /var/www/certbot
            sudo chown -R ubuntu:ubuntu /var/www/certbot

            echo "Running Go container..."
            docker run -d --name homeinsightcore --network app-network \
              -p 8000:8000 \
              $ECR_REGISTRY/homeinsightcore:latest

            echo "Running Nginx container..."
            docker run -d --name nginx --network app-network \
              -p 80:80 -p 443:443 \
              -v /etc/letsencrypt:/etc/letsencrypt \
              -v /var/www/certbot:/var/www/certbot \
              $ECR_REGISTRY/homeinsightcore_nginx:latest

            echo "Deployment completed successfully!"
