name: Deploy Go App with Nginx and SSL to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 550487074506.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Go Docker Image
        run: |
          docker build -t go-language-repo .
          docker tag go-language-repo:latest 550487074506.dkr.ecr.us-east-1.amazonaws.com/go-language-repo:latest
          docker push 550487074506.dkr.ecr.us-east-1.amazonaws.com/go-language-repo:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install AWS CLI if not available
            if ! command -v aws > /dev/null; then
              sudo apt-get update && sudo apt-get install -y awscli
            fi

            # Log in to AWS ECR
            aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 550487074506.dkr.ecr.us-east-1.amazonaws.com

            # Pull latest Docker image
            sudo docker pull 550487074506.dkr.ecr.us-east-1.amazonaws.com/go-language-repo:latest

            # Stop and remove old container (if exists)
            sudo docker stop go-language-repo || true
            sudo docker rm go-language-repo || true

            # Run the container with required env var
            sudo docker run -d --name go-language-repo -p 8000:8000 \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              550487074506.dkr.ecr.us-east-1.amazonaws.com/go-language-repo:latest
