name: Build, publish, and deploy Frontend Docker image (ECR) to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t go-lang-project .

      - name: Tag Docker image
        run: |
          docker tag go-lang-project:latest 550487074506.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/go-lang-project:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 550487074506.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/go-lang-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
                  export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
                  export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  export AWS_REGION=${{ secrets.AWS_REGION }}

                  sudo aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin 550487074506.dkr.ecr.$AWS_REGION.amazonaws.com

                   sudo docker pull 550487074506.dkr.ecr.$AWS_REGION.amazonaws.com/go-lang-project:latest

                    sudo docker stop backend || true
                   sudo docker rm backend || true

                    sudo docker run -d --name backend -p 8000:8000 550487074506.dkr.ecr.$AWS_REGION.amazonaws.com/go-lang-project:latest